In [154]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [156]:
df=pd.read_csv('User_Data.csv')

In [158]:
df.head(5)


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [160]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [162]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
395    False
396    False
397    False
398    False
399    False
Length: 400, dtype: bool

In [164]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [213]:
df.tail(5)

Age  EstimatedSalary  Purchased
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

In [166]:
df.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [207]:
df = df.drop(columns=['User ID', 'Gender'])


KeyError: "['User ID', 'Gender'] not found in axis"

In [176]:
# x=df[['Age']]
x=df.drop('Purchased',axis=1)
y=df['Purchased']

In [178]:
x.shape

(400, 2)

In [203]:
x.columns

Index(['Age', 'EstimatedSalary'], dtype='object')

In [205]:
y.name

'Purchased'

In [184]:
from sklearn.model_selection import train_test_split

In [186]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [188]:
from sklearn.linear_model import LogisticRegression

In [190]:
lr=LogisticRegression()

In [192]:
lr.fit(x_train,y_train)

LogisticRegression()

In [197]:
lr.score(x_test,y_test)*100

85.0

In [211]:
lr.predict([[19,19000]])

C:\Users\mishr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [215]:
lr.predict([[46,41000]])	

C:\Users\mishr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [217]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [222]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [224]:
df=pd.read_csv('User_Data.csv')

In [226]:
df.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [240]:
df = df.drop(columns=['User ID', 'Gender'])

In [242]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [244]:
x=df.drop('Purchased',axis=1)
y=df['Purchased']

In [246]:
x.columns

Index(['Age', 'EstimatedSalary'], dtype='object')

In [248]:
y.name

'Purchased'

In [284]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

In [320]:
ru=RandomUnderSampler()
ro=RandomOverSampler()

In [322]:
ro_x,ro_y=ro.fit_resample(x,y)

In [324]:
ru_x,ru_y=ru.fit_resample(x,y)

In [326]:
ru_x

Age  EstimatedSalary
70    25            80000
284   48           141000
129   26            84000
169   29            47000
130   31            58000
..   ...              ...
393   60            42000
395   46            41000
396   51            23000
397   50            20000
399   49            36000

[286 rows x 2 columns]

In [328]:
ru_x.value_counts()

Age  EstimatedSalary
41   72000              4
48   33000              2
38   61000              2
28   59000              2
24   55000              2
                       ..
35   72000              1
     73000              1
     88000              1
     91000              1
60   108000             1
Name: count, Length: 270, dtype: int64

In [330]:
ro_y.value_counts()

Purchased
0    257
1    257
Name: count, dtype: int64

In [332]:
ru_y.value_counts()

Purchased
0    143
1    143
Name: count, dtype: int64

In [334]:
from sklearn.model_selection import train_test_split

In [336]:
x_train,x_test,y_train,y_test=train_test_split(ru_x,ru_y,test_size=0.3,random_state=42)

In [338]:
from sklearn.linear_model import LogisticRegression

In [302]:
lr=LogisticRegression()

In [304]:
lr.fit(x_train,y_train)

LogisticRegression()

In [306]:
lr.score(x_test,y_test)*100

80.23255813953489

In [379]:
 lr.predict([[19,19000]])


C:\Users\mishr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [372]:
lr.predict([[46,41000]])	

C:\Users\mishr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [340]:
from sklearn.model_selection import train_test_split

In [346]:
x1_train,x1_test,y1_train,y1_test=train_test_split(ro_x,ro_y,test_size=0.3,random_state=42)

In [348]:
from sklearn.linear_model import LogisticRegression

In [350]:
lr1=LogisticRegression()

In [352]:
lr1.fit(x1_train,y1_train)

LogisticRegression()

In [354]:
lr1.score(x1_test,y1_test)*100

82.58064516129032

In [356]:
lr1.predict([[19,19000]])

C:\Users\mishr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [358]:
lr1.predict([[46,41000]])	

C:\Users\mishr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [362]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [387]:
accuracy = lr.score(x_test, y_test)
y_pred = lr.predict(x_test)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [393]:
print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.7790697674418605
Confusion Matrix:
[[34  8]
 [11 33]]
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.81      0.78        42
           1       0.80      0.75      0.78        44

    accuracy                           0.78        86
   macro avg       0.78      0.78      0.78        86
weighted avg       0.78      0.78      0.78        86

